# en.toml
Name="🇺🇸 English"

Trip = "🛬 {{.StartDate}} > 🛫 {{.EndDate}}, Duration: {{.TripDays}}, with Total: "
TripPredicted = "🛬 {{.StartDate}} > Leave until 🛫 {{.EndDate}}, Duration: {{.TripDays}}, with Total:"
TripPast = "Previous Trips:"
TripEligibleHdr = "You're eligible for the following trips:"
TripEligible = "🛬 {{.StartDate}} > 🛫 {{.EndDate}}, Duration: {{.TripDays}}, with Total: "
TripExplanation = "Depending on your country you're allowed to stay in Turkey for a while, basically, there are 3 metrics that you need to look at:\nContinual Days - days that you're allowed to stay without crossing the Turkey border,\nDays Limit - days that you spent in Turkey during some interval,\nInterval Reset - days you spent above the reset interval are not counted, in case you're not breaking other limits."

UserInfo = "Language: {{.Language}}"
UserLanguageChaned = "Language Changed"
UserCountryChaned = "Country Changed"

CountryInfo = "Country: {{.Flag}} {{.Name}}"
CountryDays = "Days Allowed - Continual: {{.Continual}} / Limit: {{.Limit}} / Reset Interval: {{.ResetInterval}}"

[DayCounter]
description = "Display day/days on condition"
one = "{{.Count}} day"
other = "{{.Count}} days"
