# ru.toml
HelloMessage = "Привет Мир!"
Trip = "Поездка: {{.StartDate}} - {{.EndDate}}, непрерывно: {{.TripDays}}, в пределах лимита: "
TripPredicted = "{{.StartDate}}, при выезде {{.EndDate}} будет использовано {{.TripDays}} из "
TripPast = "Прошлые поездки:"
UserInfo = "Язык: {{.Language}}"
CountryInfo = "Страна: {{.Code}} {{.Flag}}"
CountryDays = "Дней разрешено - Единовременно: {{.Continual}} / Всего: {{.Limit}} / Обнуление: {{.ResetInterval}}"
DaysExplanation = "В зависимости от вашей страны вы можете находиться в Турции некоторое время, существуют 3 основных показателя:\nНепрерывное пребываение - дни, которые вы можете находиться на территории республики без пересечения границы,\nЛимит дней - лимит нахождения на территории Турции за определенный период,\nОбнуление срока - дни пребывания за пределами срока обнуления не учитываются, в случае если вы не превышали других лимитов."

[DayCounter]
description = "Показывает день/дня/дней в зависимости от количества"
one = "{{.Count}} день"
few = "{{.Count}} дня"
many = "{{.Count}} дней"
