# ru.toml
Name="🇷🇺 Русский"

Trip = "🛬 {{.StartDate}} > 🛫 {{.EndDate}}, длительность: {{.TripDays}}, за период: "
TripPredicted = "🛬 {{.StartDate}} > выезд до 🛫 {{.EndDate}}, длительность: {{.TripDays}}, за период: "
TripPast = "Прошлые поездки:"
TripEligibleHdr = "Допустимые сроки поездок:"
TripEligible = "🛬 {{.StartDate}} > 🛫 {{.EndDate}}, длительность: {{.TripDays}}, за период: "
TripExplanation = "В зависимости от вашей страны вы можете находиться в Турции некоторое время, существуют 3 основных показателя:\nНепрерывное пребываение - дни, которые вы можете находиться на территории республики без пересечения границы,\nЛимит дней - лимит нахождения на территории Турции за определенный период,\nОбнуление срока - дни пребывания за пределами срока обнуления не учитываются, в случае если вы не превышали других лимитов."

UserInfo = "Язык: {{.Language}}"
UserLanguageChaned = "Язык изменен"
UserCountryChaned = "Country Changed"

CountryInfo = "Страна: {{.Flag}} {{.Code}}"
CountryDays = "Дней разрешено - Единовременно: {{.Continual}} / Всего: {{.Limit}} / Обнуление: {{.ResetInterval}}"

[DayCounter]
description = "Показывает день/дня/дней в зависимости от количества"
one = "{{.Count}} день"
few = "{{.Count}} дня"
many = "{{.Count}} дней"
